Algoritmo "jogodavelha"

Var
  m: vetor [1..3, 1..3] de inteiro
  l, c: inteiro
  i: inteiro



Procedimento Mostra_matriz ()
Inicio
  Escreval ("+---+---+---+")
    Para l <- 1 ate 3 faca
      Escreval ("| ", v[l,c]:1)
    FimPara
    Escreval ("|")
    Escreval ()
    Escreval ("+---+---+---+")
  FimPara
FimProcedimento













Inicio


    Escreval ("+---+---+---+")
    Escreva ("|":4, "|":4, "|":4, "|":4)


Fimalgoritmo